# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: é¦–é¡µ
  url: /
  icon:
- page: iOS
  url: /categories/iOS/
  icon:
- page: Python
  url: /categories/Python/
  icon:
- page: Linux
  url: /categories/Linux/
  icon:
# - page: ç®—æ³•
#   url: /categories/Algorithm/
#   icon:
- page: å…¶å®ƒ
  url: /categories/Others/
  icon:
# - page: èµ„æº
#   url: /categories/èµ„æº/
  # icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: './img/head-img.jpg'
  url: 'javascript:'

# å„ä¸ªå°å·¥å…·çš„è®¾ç½®

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends


## æœç´¢
jsonContent:
  searchLocal: true
  searchGoogle: true
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## ç½‘ç«™å…¬å‘Šè®¾ç½®
notification: |-
            <div class="clock">
              <div style="margin:10px auto 10px auto; overflow:hidden;">
                <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="300" height="100">
                  <param name="movie" value="./img/flash/clock.swf">
                  <param name="quality" value="high">
                  <param name="wmode" value="transparent">
                  <embed src="./img/flash/clock.swf" quality="high" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="300" height="100">
                </object>
              </div>
            </div>
            <div class="hamster" style="margin-top: 17px;">
              <div style="margin:10px auto 10px auto; overflow:hidden;">
                <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="300" height="200">
                  <param name="movie" value="./img/flash/hamster.swf">
                  <param name="quality" value="high">
                  <param name="wmode" value="transparent">
                  <embed src="./img/flash/hamster.swf" quality="high" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="300" height="200">
                </object>
              </div>
            </div>
            <div class="content" style="text-align:center;">
              <p>
                Welcome to LinXunFeng's blog ğŸš€ğŸš€ğŸš€
              </p>
            </div>
            

## ç¤¾äº¤è®¾ç½®
social:
 - name: Github
   icon: git
   href: //github.com/LinXunFeng
 - name: é‚®ç®±
   icon: envelope-o
   href: mailto:xunfenghellolo@gmail.com
#  - name: è”ç³»QQ
#    icon: qq
#    href: /
#  - name: å¾®ä¿¡
#    icon: weixin
#    href: /
#  - name: QQç¾¤
#    icon: users
#    href: /
 - name: æ˜é‡‘
   icon: forumbee
   href: //juejin.im/user/58f8065e61ff4b006646c72d/posts
 - name: ç®€ä¹¦
   icon: book
   href: //www.jianshu.com/u/31e85e7a22a2
 - name: RSS
   icon: feed
   href: /atom.xml

## æ–‡ç« åˆ†ç±»è®¾ç½®
cate_config:
   show_count: true
   show_current: true

## æ–‡ç« å½’æ¡£è®¾ç½®
arch_config:
   type: 'monthly'
   format: 'YYYYå¹´MMæœˆ'
   show_count: true
   order: -1

## æ ‡ç­¾äº‘è®¾ç½®
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## å‹é“¾è®¾ç½®
links:
  - æ˜é‡‘: https://juejin.im/user/58f8065e61ff4b006646c72d/posts
  - ç®€ä¹¦: https://www.jianshu.com/u/31e85e7a22a2


# ä¸»é¢˜è‡ªå®šä¹‰ä¸ªæ€§åŒ–é…ç½®

## ç½‘ç«™å®£ä¼ è¯­
branding:

## è®¾ç½®bannerèƒŒæ™¯å›¾ç‰‡
banner:
    img: ./img/background/banner.jpeg

## é¦–é¡µåˆ—è¡¨åº•éƒ¨é¢æ¿
homePanel: true

## ç¼©ç•¥å›¾è‡ªå®šä¹‰éšæœºå›¾ç‰‡
defaultImgs:
  -

## æˆªå–æ–‡ç« é¦–é¡µæè¿°å­—æ•°
excerptLength: 120

## æ˜¯å¦å¼€å¯æ–‡ç« ç›®å½•
toc: true

## ä»£ç é«˜äº®é…ç½®
highlightTheme:

## bootstrapé…ç½®
bootstrap:

## ICONé…ç½®
fontAwesome:

## æ–‡ç« è¿‡æœŸæé†’åŠŸèƒ½
warning:
  days: 300
  text: 'æœ¬æ–‡äº%då¤©ä¹‹å‰å‘è¡¨ï¼Œæ–‡ä¸­å†…å®¹å¯èƒ½å·²ç»è¿‡æ—¶ã€‚'

## æ–‡ç« å†…å£°æ˜
declaration:
  enable: true
  title: 'è½¬è½½å£°æ˜'
  tip: |-
      å•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒ,éå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ Â© <a href="http://linxunfeng.top/" target="_blank">LinXunFeng</a>

## æ–‡ç« æ‰“èµ
reward:
  alipay: 'http://linxunfeng.github.io/img/pay/alipay.png'
  wepay: 'http://linxunfeng.github.io/img/pay/wechat.png'
  tip: èµèµæ˜¯ä¸è€æµæ°“çš„é¼“åŠ±

## ä¸»é¢˜è¯„è®º

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### æ¥å¿…åŠ›
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### å‹è¨€è¯„è®º(æœåŠ¡ä¸ç¨³å®š)
uyan:
  enable: false
  uyan_id: 1966422

### Disqusè¯„è®º
disqus:
  enable: false
  shortname: snippet
  count: false

### ç•…è¨€è¯„è®º(éœ€è¦ICPå¤‡æ¡ˆ)
changyan:
  enable: false
  appid:
  conf:

## Valineè¯„è®º
valine:
   enable: true
   appId: 0rTljoibiQOAeo1tQ9qXExq9-gzGzoHsz
   appKey: 2N2gdmSHN6mIGpbmX8duHv6X
   placeholder: è¯´ç‚¹ä»€ä¹ˆå§
   notify: true
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

## ç½‘ç«™è®¿å®¢ç»Ÿè®¡
visit_counter:
   site: true
   page: true

## ç½‘ç«™è®¿é—®ç»Ÿè®¡åˆ†æ

### ç½‘ç›ŸCNZZç»Ÿè®¡
cnzz_analytics: 1275838195

### ç™¾åº¦ç»Ÿè®¡
baidu_analytics: 031981f555deecc203818690c85ef421

### è°·æ­Œç»Ÿè®¡
google_analytics: UA-131541294-1

### è…¾è®¯åˆ†æ
tencent_analytics: 66150761

### ç™¾åº¦ç«™ç‚¹è®¤è¯
baidu_site_verification: 9LgZ2AlWYS

### ç™¾åº¦è‡ªåŠ¨æ¨é€
baidu_push: true

#ç½‘ç«™ä¸»é¢˜é…ç½®
since: 2017
robot: 'all' ### æ§åˆ¶æœç´¢å¼•æ“çš„æŠ“å–å’Œç´¢å¼•ç¼–åˆ¶è¡Œä¸ºï¼Œé»˜è®¤ä¸ºall
version: 1.2.1
